services:
  items-api:
    build: .
    ports:
      - "8000:8000"
  
  visualizador-db:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./DB_sqlite:/data
    environment:
      - SQLITE_DATABASE=datos.db

